# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_menu_module', to='team.Module'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set([('reference',)]),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([('name', 'module')]),
        ),
    ]
