# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20161006_1947'),
        ('menu', '0003_auto_20161010_0301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([('module',)]),
        ),
    ]
