# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20161010_0305'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([]),
        ),
    ]
