# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20161010_0907'),
        ('menu', '0005_auto_20161010_1347'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([('module',)]),
        ),
    ]
