# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20161010_1756'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([('name',)]),
        ),
    ]
