# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20161010_1757'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set([]),
        ),
    ]
