# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_auto_20161014_0103'),
        ('menu', '0009_auto_20161010_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_teammenu_module', to='menu.Menu')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_teammenu_team', to='team.Team')),
            ],
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TeamSubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_teamsubmenu_menu_item', to='menu.MenuItem')),
                ('team_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_teamsubmenu_team_menu', to='menu.TeamMenu')),
            ],
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='teamsubmenu',
            unique_together=set([('team_menu', 'menu_item')]),
        ),
        migrations.AlterUniqueTogether(
            name='teammenu',
            unique_together=set([('team', 'menu')]),
        ),
    ]
