# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20161014_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=100)),
            ],
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='permissionsmenu',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='teamsubmenu',
            name='permission_menu',
            field=models.ManyToManyField(related_name='menu_teamsubmenu_permission_menu', to='menu.PermissionsMenu'),
        ),
    ]
