# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_auto_20161014_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_teammenuitem_menu_item', to='menu.MenuItem')),
                ('permission_menu', models.ManyToManyField(related_name='menu_teammenuitem_permission_menu', to='menu.MenuPermissions')),
                ('team_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_teammenuitem_team_menu', to='menu.TeamMenu')),
            ],
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='teamsubmenu',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='teamsubmenu',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='teamsubmenu',
            name='permission_menu',
        ),
        migrations.RemoveField(
            model_name='teamsubmenu',
            name='team_menu',
        ),
        migrations.DeleteModel(
            name='TeamSubMenu',
        ),
        migrations.AlterUniqueTogether(
            name='teammenuitem',
            unique_together=set([('team_menu', 'menu_item')]),
        ),
    ]
