# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_auto_20161014_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammenuitem',
            name='permission_menu',
        ),
        migrations.AddField(
            model_name='teammenuitem',
            name='permissions_menu',
            field=models.ManyToManyField(related_name='menu_teammenuitem_permissions_menu', to='menu.MenuPermissions'),
        ),
        migrations.AlterField(
            model_name='teammenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_teammenu_menu', to='menu.Menu'),
        ),
    ]
