# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0002_auto_20161006_1228'),
        ('core', '0019_auto_20161006_1124'),
        ('product', '0003_auto_20161006_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('igv_tax', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_quotationmaintenance_client', to='core.Person')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_quotationmaintenance_exchange_rate', to='core.Currency')),
                ('exchange_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_quotationmaintenance_exchange_rate', to='core.ExchangeRate')),
                ('vehicle_plaque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_quotationmaintenance_vehicle_plaque', to='vehicle.Vehicle')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='QuotationMaintenanceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_quotationmaintenancedetail_product', to='product.Product')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_quotationmaintenancedetail_product_category', to='product.ProductCategory')),
                ('product_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_quotationmaintenancedetail_product_subcategory', to='product.ProductSubCategory')),
                ('quotation_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_quotationmaintenancedetail_quotation_maintenance', to='quotation.QuotationMaintenance')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
    ]
