# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_auto_20161015_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationstoredetail',
            name='quotation_supplier',
        ),
        migrations.AddField(
            model_name='quotationstoredetail',
            name='quotation_store',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quotation_quotationstoredetail_quotation_store', to='quotation.QuotationStore'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotationstore',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_quotationstore_supplier', to='supplier.Supplier'),
        ),
    ]
