# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_auto_20161015_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationstore',
            name='igv_tax',
        ),
        migrations.RemoveField(
            model_name='quotationstore',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='quotationstore',
            name='total_paid',
        ),
        migrations.RemoveField(
            model_name='quotationstoredetail',
            name='amount_price',
        ),
        migrations.RemoveField(
            model_name='quotationstoredetail',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='quotationstoredetail',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
