# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0006_auto_20161015_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationstore',
            name='code_qt_store',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
