# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0008_auto_20161016_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationstoredetail',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
