# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20161006_0133'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_product_brand', to='core.ProductBrand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_product_model', to='core.ProductModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_product_unit', to='core.UnitMeasurement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdetail',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='origin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='product',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_productdetail_product', to='product.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdetail',
            name='series',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('product_category', 'product_subcategory', 'name')]),
        ),
    ]
