# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20161006_0149'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsubcategory',
            unique_together=set([('product_category', 'name')]),
        ),
    ]
