# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_auto_20161005_1318'),
        ('taller', '0003_purchaseorderstore_purchaseorderstoredetail'),
        ('vehicle', '0002_auto_20161006_1228'),
        ('product', '0003_auto_20161006_0149'),
        ('core', '0019_auto_20161006_1124'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceGuideTallerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('date', models.DateField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_referenceguidetallerorder_applicant', to='customer.UserProfile')),
                ('order_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_referenceguidetallerorder_purchase_order_store', to='taller.PurchaseOrderStore')),
                ('store_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_referenceguidetallerorder_store_destination', to='core.Store')),
                ('subsidiary', models.ManyToManyField(related_name='store_referenceguidetallerorder_subsidiary', to='company.Subsidiary')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceGuideTallerOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_referenceguidetallerorderdetail_product', to='product.Product')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_referenceguidetallerorderdetail_purchase_order_store', to='store.ReferenceGuideTallerOrder')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_referenceguidetallerorderdetail_vehicle', to='vehicle.Vehicle')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
    ]
