# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160911_2147'),
        ('client', '0002_auto_20160911_2147'),
        ('employee', '0001_initial'),
        ('taller', '0006_auto_20160910_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('taxi_driver', models.CharField(blank=True, max_length=200, null=True)),
                ('destination', models.CharField(blank=True, max_length=200, null=True)),
                ('date_arrival', models.DateTimeField(blank=True, null=True)),
                ('hour_arrival', models.TimeField(blank=True, null=True)),
                ('fuel_arrival', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unit_number_arrival', models.CharField(blank=True, max_length=45, null=True)),
                ('km_arrival', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('date_exit', models.DateTimeField(blank=True, null=True)),
                ('hour_exit', models.TimeField(blank=True, null=True)),
                ('fuel_exit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unit_number_exit', models.CharField(blank=True, max_length=45, null=True)),
                ('km_exit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('kms_next_maintenance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('number_billing', models.PositiveIntegerField(blank=True, null=True)),
                ('number_contract', models.CharField(blank=True, max_length=45, null=True)),
                ('status_order', models.CharField(choices=[('TA3-1', 'Checklist'), ('TA3-2', 'Solicitud de Mantenimiento'), ('TA3-3', 'Diagnostico Realizado'), ('TA3-4', 'Pendiente'), ('TA3-5', 'En Proceso'), ('TA3-6', 'Finalizado')], max_length=10)),
                ('type_order', models.CharField(choices=[('TA4-1', 'Alquiler'), ('TA4-2', 'Mantenimiento'), ('TA4-3', 'Supervision')], max_length=10)),
                ('observation_delivery', models.TextField(blank=True, null=True)),
                ('observation_refund', models.TextField(blank=True, null=True)),
                ('observation_inspection', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_order_client', to='client.Person')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_order_subsidiary', to='core.Subsidiary')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('status_order', models.CharField(choices=[('TA3-4', 'Pendiente'), ('TA3-5', 'En Proceso'), ('TA3-6', 'Finalizado')], max_length=3)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_orderdetail_employee', to='employee.Employee')),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_orderdetail_labour', to='taller.Labour')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_orderdetail_order', to='taller.Order')),
                ('type_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_orderdetail_type_vehicle', to='taller.TypeVehicle')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('file_image', models.FileField(upload_to='checklists/%Y/%m/%d/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_orderdocument_order', to='taller.Order')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderSupervision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('observation', models.TextField()),
                ('job_rating', models.CharField(blank=True, max_length=45, null=True)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_ordersupervision_employee', to='employee.Employee')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_ordersupervision_order_detail', to='taller.OrderDetail')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TypeCheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TypeFuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('type_fuel', models.CharField(choices=[('TA2-1', 'Fuel Output'), ('TA2-2', 'Fuel Income')], max_length=100)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='quotation',
            name='current_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status_vehicle',
            field=models.CharField(choices=[('TA1-1', 'Alquilado'), ('TA1-2', 'Mantenimient Income'), ('TA1-3', 'Disponible')], max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='type_checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_order_type_checklist', to='taller.TypeCheckList'),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_order_vehicle', to='taller.Vehicle'),
        ),
    ]
