# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 15:33
from __future__ import unicode_literals

import core.custom_upload
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContributionSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('number_account', models.CharField(blank=True, max_length=20, null=True)),
                ('plame', models.CharField(blank=True, max_length=12, null=True)),
                ('percentage_bonus', models.DecimalField(decimal_places=4, default=0, max_digits=8, null=True)),
                ('top', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Correlative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('type_correlative', models.CharField(choices=[('CRT-1', 'Factura'), ('CRT-2', 'Boleta'), ('CRT-3', 'Cotizacion'), ('CRT-4', 'Checklist')], max_length=2)),
                ('prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('postfix', models.CharField(blank=True, max_length=20, null=True)),
                ('format', models.CharField(blank=True, max_length=20, null=True)),
                ('initial', models.IntegerField(default=1)),
                ('increment', models.IntegerField(default=1)),
                ('final', models.IntegerField(blank=True, null=True)),
                ('actual', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('iso_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('sk', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_fund', models.BooleanField(default=False)),
                ('is_complimentary', models.BooleanField(default=False)),
                ('is_metal', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_exchangerate_currency', to='core.Currency')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('current_status', models.CharField(choices=[('', '--Choose--'), ('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], default='ENABLED', max_length=10)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('reason_social', models.CharField(blank=True, max_length=100, null=True)),
                ('initial_exercise', models.DateTimeField(blank=True, null=True)),
                ('final_initial_exercise', models.DateTimeField(blank=True, null=True)),
                ('nit', models.CharField(blank=True, max_length=20, null=True)),
                ('legal_representative', models.CharField(blank=True, max_length=100, null=True)),
                ('accountant', models.CharField(blank=True, max_length=100, null=True)),
                ('register_accountant', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('logo_url', models.ImageField(blank=True, null=True, upload_to=core.custom_upload.upload_location_organization)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_organization_currency', to='core.Currency')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_state_country', to='core.Country')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_subsidiary_organization', to='core.Organization')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('current_status', models.CharField(choices=[('', '--Choose--'), ('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], default='ENABLED', max_length=10)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_team_group', to='auth.Group')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_team_module', to='core.Module')),
            ],
            options={
                'ordering': ['date_created'],
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TypeContributionSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('type_contribution', models.CharField(choices=[('CTS-1', 'ONP'), ('CTS-2', 'AFP'), ('CTS-3', 'ESSALUD'), ('CTS-4', 'EPS'), ('CTS-5', 'SCTR-SALUD'), ('CTS-6', 'SCTR-PENSION')], max_length=1)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UnitMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('type_correlative', models.CharField(choices=[('UPM-1', 'PURCHASE UNIT'), ('UPM-2', 'PURCHASE UNIT'), ('UPM-3', 'TRANSPORT UNIT'), ('UPM-4', 'DELIVERY UNIT'), ('UPM-5', 'STORAGE UNIT')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_state_zone', to='core.Zone'),
        ),
        migrations.AddField(
            model_name='country',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_country_zone', to='core.Zone'),
        ),
        migrations.AddField(
            model_name='correlative',
            name='subsidiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_correlative_subsidiary', to='core.Subsidiary'),
        ),
        migrations.AddField(
            model_name='contributionsystem',
            name='type_contribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_contributionsystem_type_contribution', to='core.TypeContributionSystem'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('group', 'module')]),
        ),
    ]
