# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161004_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('plaque', models.CharField(blank=True, max_length=200, null=True)),
                ('year_car', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('serie_motor', models.CharField(blank=True, max_length=200, null=True)),
                ('soat', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_soat', models.DateTimeField(blank=True, null=True)),
                ('poliza', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_poliza', models.DateTimeField(blank=True, null=True)),
                ('technical_review', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_technical_review', models.DateTimeField(blank=True, null=True)),
                ('opacity_test', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_opacity_test', models.DateTimeField(blank=True, null=True)),
                ('farenet_test', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_farenet_test', models.DateTimeField(blank=True, null=True)),
                ('type_vehicle', models.CharField(blank=True, choices=[('', '--Choose--'), ('VHL-1', 'LIGHTWEIGHT'), ('VHL-2', 'HEAVY')], max_length=20, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_vehicle_brand', to='core.Brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_vehicle_brand', to='core.Model')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='contributionsystem',
            name='plame',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='typecontributionsystem',
            name='type_contribution',
            field=models.CharField(choices=[('CTS-1', 'ONP'), ('CTS-2', 'AFP'), ('CTS-3', 'ESSALUD'), ('CTS-4', 'EPS'), ('CTS-5', 'SCTR-SALUD'), ('CTS-6', 'SCTR-PENSION')], max_length=20),
        ),
        migrations.AlterField(
            model_name='unitmeasurement',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unitmeasurement',
            name='type_measurement',
            field=models.CharField(choices=[('UPM-1', 'PURCHASE LIQUID UNIT'), ('UPM-2', 'PURCHASE SOLID UNIT'), ('UPM-3', 'TRANSPORT UNIT'), ('UPM-4', 'DELIVERY UNIT'), ('UPM-5', 'STORAGE UNIT')], max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type_transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_vehicle_type_transport', to='core.UnitMeasurement'),
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together=set([('name',)]),
        ),
    ]
