# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161004_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('year', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='core_model_brand', to='core.Brand'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_enrollment_brand', to='core.Brand'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_enrollment_model', to='core.Model'),
        ),
    ]
