# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161004_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_enrollmentmodel_brand', to='core.Brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_enrollmentmodel_model', to='core.Model')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='model',
        ),
        migrations.AddField(
            model_name='enrollmentmodel',
            name='year',
            field=models.ManyToManyField(related_name='core_enrollmentmodel_year', to='core.Enrollment'),
        ),
    ]
