# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161005_0038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollmentmodel',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='enrollmentmodel',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='enrollmentmodel',
            name='model',
        ),
        migrations.RemoveField(
            model_name='enrollmentmodel',
            name='year',
        ),
        migrations.DeleteModel(
            name='EnrollmentModel',
        ),
    ]
