# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_fuel_unit_transport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fuel',
            unique_together=set([('name', 'unit_transport')]),
        ),
    ]
