# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20161005_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleFuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('unit_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_vehiclefuel_type_transport', to='core.UnitMeasurement')),
            ],
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameModel(
            old_name='Brand',
            new_name='VehicleBrand',
        ),
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='VehicleEnrollment',
        ),
        migrations.AlterUniqueTogether(
            name='fuel',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='fuel',
            name='unit_transport',
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='model',
            name='brand',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_vehicle_model', to='core.VehicleModel'),
        ),
        migrations.DeleteModel(
            name='Fuel',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_vehiclemodel_brand', to='core.VehicleBrand'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclemodel',
            unique_together=set([('brand', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclefuel',
            unique_together=set([('name', 'unit_transport')]),
        ),
    ]
