# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20161006_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='unit_transport',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
