# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20161007_1347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutoInventory',
            new_name='VehicleInventory',
        ),
    ]
