# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20161008_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person_type',
        ),
        migrations.AddField(
            model_name='person',
            name='person_tribute',
            field=models.CharField(blank=True, choices=[('', '--Choose--'), ('PERS-1', 'Natural'), ('PERS-2', 'Legal')], max_length=20, null=True),
        ),
    ]
