# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20161008_1352'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together=set([('sk', 'code', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set([('email',)]),
        ),
    ]
