# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 04:36
from __future__ import unicode_literals

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('description', models.TextField()),
                ('cost_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('sale_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TypeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TypeVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('plaque', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True)),
                ('year_car', models.PositiveSmallIntegerField()),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('serie_motor', models.CharField(blank=True, max_length=200, null=True)),
                ('soat', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_soat', models.DateTimeField(blank=True, null=True)),
                ('poliza', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_poliza', models.DateTimeField(blank=True, null=True)),
                ('technical_review', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_technical_review', models.DateTimeField(blank=True, null=True)),
                ('opacity_test', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_opacity_test', models.DateTimeField(blank=True, null=True)),
                ('farenet_test', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_farenet_test', models.DateTimeField(blank=True, null=True)),
                ('is_flotilla', models.BooleanField(default=False)),
                ('status_vehicle', models.CharField(blank=True,
                                                    choices=[('TA1-1', 'Alquilado'), ('TA1-2', 'Mantenimiento'),
                                                             ('TA1-3', 'Disponible')], max_length=100, null=True)),
                ('brand',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_vehicle_brand',
                                   to='taller.Brand')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='taller_vehicle_subsidiary', to='core.Subsidiary')),
                ('type_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='taller_vehicle_type_vehicle',
                                                   to='taller.TypeVehicle')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='labour',
            name='type_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='taller_labour_type_vehicle', to='taller.TypeVehicle'),
        ),
    ]
