# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 03:06
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_currency_exchangerate'),
        ('client', '0001_initial'),
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('igv_tax', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('sub_total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_paid', models.DecimalField(decimal_places=4, max_digits=18)),
                ('current_date', models.DateField()),
                ('client',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_quotation_person',
                                   to='client.Person')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='taller_quotation_currency', to='core.Currency')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='QuotationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('amount_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                related_name='taller_quotationdetail_quotation',
                                                to='taller.Quotation')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='expiration_farenet_test',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 10, 3, 6, 2, 414173), null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='expiration_opacity_test',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 10, 3, 6, 2, 414149), null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='expiration_poliza',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 10, 3, 6, 2, 414097), null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='expiration_soat',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 10, 3, 6, 2, 414056), null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='expiration_technical_review',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 10, 3, 6, 2, 414125), null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='taller_quotation_vehicle', to='taller.Vehicle'),
        ),
    ]
