# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('taller', '0002_auto_20160910_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='expiration_farenet_test',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='expiration_opacity_test',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='expiration_poliza',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='expiration_soat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='expiration_technical_review',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
