# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20161005_1318'),
        ('vehicle', '0002_auto_20161006_1228'),
        ('product', '0003_auto_20161006_0149'),
        ('customer', '0001_initial'),
        ('taller', '0002_remove_labour_unit_transport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('date', models.DateField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_purchaseorderstore_applicant', to='customer.UserProfile')),
                ('subsidiary', models.ManyToManyField(related_name='taller_purchaseorderstore_subsidiary', to='company.Subsidiary')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderStoreDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('observation', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_purchaseorderstoredetail_product', to='product.Product')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_purchaseorderstoredetail_product_category', to='product.ProductCategory')),
                ('product_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_purchaseorderstoredetail_product_subcategory', to='product.ProductSubCategory')),
                ('purchase_order_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_purchaseorderstoredetail_purchase_order_store', to='taller.PurchaseOrderStore')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taller_purchaseorderstoredetail_vehicle', to='vehicle.Vehicle')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
    ]
