# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0007_auto_20160911_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status_vehicle',
            field=models.CharField(choices=[('TA1-1', 'Alquilado'), ('TA1-2', 'Mantenimient Income'), ('TA1-3', 'Disponible')], default='TA1-1', max_length=10),
        ),
    ]
