# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='document_type',
            field=models.CharField(blank=True, choices=[('', '--Choose--'), ('DOC-1', 'DNI'), ('DOC-2', 'RUC'), ('DOC-3', 'PASSPORT')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(blank=True, choices=[('', '--Choose--'), ('PERS-1', 'Natural'), ('PERS-2', 'Juridical')], max_length=20, null=True),
        ),
    ]
