# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0018_auto_20161006_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('plaque', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('type_vehicle', models.CharField(blank=True, choices=[('', '--Choose--'), ('VHL-1', 'LIGHTWEIGHT'), ('VHL-2', 'HEAVY')], max_length=20, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_vehicle_brand', to='core.VehicleBrand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_vehicle_model', to='core.VehicleModel')),
                ('unit_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_vehicle_type_transport', to='core.UnitMeasurement')),
                ('year_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_vehicle_year_car', to='core.VehicleEnrollment')),
            ],
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('serie_motor', models.CharField(blank=True, max_length=200, null=True)),
                ('soat', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_soat', models.DateTimeField(blank=True, null=True)),
                ('poliza', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_poliza', models.DateTimeField(blank=True, null=True)),
                ('technical_review', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_technical_review', models.DateTimeField(blank=True, null=True)),
                ('opacity_test', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_opacity_test', models.DateTimeField(blank=True, null=True)),
                ('farenet_test', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_farenet_test', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_vehicledetail_vehicle', to='vehicle.Vehicle')),
            ],
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vehicledetail',
            unique_together=set([('vehicle',)]),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together=set([('unit_transport', 'brand', 'model', 'plaque')]),
        ),
    ]
