# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 14:37
from __future__ import unicode_literals

import core.utils.upload_folder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20161012_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to=core.utils.upload_folder.upload_vehicle_image),
        ),
    ]
