# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('style', models.CharField(blank=True, max_length=20, null=True)),
                ('match', models.CharField(default='#', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_menu_module', to='core.Module')),
            ],
            options={
                'ordering': ['order'],
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('style', models.CharField(blank=True, max_length=20, null=True)),
                ('match', models.CharField(default='#', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_menuitem_menu', to='menu.Menu')),
            ],
            options={
                'ordering': ['menu'],
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set([('reference',)]),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([('name', 'module')]),
        ),
    ]
