# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='accountant',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='nit',
            new_name='document_number',
        ),
        migrations.RenameField(
            model_name='subsidiary',
            old_name='name',
            new_name='representative',
        ),
        migrations.RemoveField(
            model_name='correlative',
            name='type_correlative',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='final_exercise',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='initial_exercise',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='legal_representative',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='reason_social',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='register_accountant',
        ),
        migrations.AddField(
            model_name='correlative',
            name='organization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='company_correlative_organization', to='company.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correlative',
            name='type_document',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='company_correlative_type_document', to='billing.TypeDocument'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='document_type',
            field=models.CharField(blank=True, choices=[('DOC-2', 'RUC')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='subsidiary_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
