# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20161005_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='document_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='document_type',
            field=models.CharField(choices=[('DOC-2', 'RUC')], max_length=20),
        ),
    ]
