# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_auto_20161005_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('business_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('document_type', models.CharField(blank=True, choices=[('DOC-2', 'RUC')], max_length=20, null=True)),
                ('document_number', models.CharField(blank=True, max_length=20, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('subsidiary', models.ManyToManyField(related_name='supplier_supplier_subsidiary', to='company.Subsidiary')),
            ],
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together=set([('business_name',)]),
        ),
    ]
