# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20161006_0149'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('product', models.ManyToManyField(related_name='supplier_supplierproduct_product', to='product.Product')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_supplierproduct_supplier', to='supplier.Supplier')),
            ],
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='supplierproduct',
            unique_together=set([('supplier',)]),
        ),
    ]
