# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_auto_20161012_1713'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplierproduct',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='suppliersubsidiary',
            unique_together=set([]),
        ),
    ]
