# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('current_status', models.CharField(choices=[('', '--Choose--'), ('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], default='ENABLED', max_length=10)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_groupmodule_group', to='auth.Group')),
            ],
            options={
                'ordering': ['date_created'],
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('current_status', models.CharField(choices=[('', '--Choose--'), ('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], default='ENABLED', max_length=10)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='groupmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_groupmodule_module', to='team.Module'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmodule',
            unique_together=set([('group', 'module')]),
        ),
    ]
