# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20161006_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodule',
            name='module',
        ),
        migrations.AddField(
            model_name='groupmodule',
            name='module',
            field=models.ManyToManyField(related_name='team_groupmodule_module', to='team.Module'),
        ),
    ]
