# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20161010_1810'),
        ('auth', '0008_alter_user_username_max_length'),
        ('team', '0006_auto_20161010_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('current_status', models.CharField(choices=[('', '--Choose--'), ('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], default='ENABLED', max_length=10)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_team_group', to='auth.Group')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_teammenu_group', to='team.Team')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_teammenu_module', to='menu.Menu')),
            ],
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TeamModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_teammodule_module', to='team.Module')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_teammodule_team', to='team.Team')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TeamSubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('group_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_teamsubmenu_group_menu', to='team.TeamMenu')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_teamsubmenu_menu_item', to='menu.MenuItem')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='groupmodule',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='groupmodule',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmodule',
            name='module',
        ),
        migrations.DeleteModel(
            name='GroupModule',
        ),
        migrations.AlterUniqueTogether(
            name='teammenu',
            unique_together=set([('group', 'menu')]),
        ),
    ]
