# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20161013_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_team_group', to='auth.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([]),
        ),
    ]
