# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_auto_20161013_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='module',
            field=models.ManyToManyField(related_name='team_team_module', through='team.TeamModule', to='team.Module'),
        ),
    ]
