# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20161010_1810'),
        ('team', '0011_auto_20161013_2111'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamsubmenu',
            unique_together=set([('group_menu', 'menu_item')]),
        ),
    ]
