# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_auto_20161013_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='module',
        ),
    ]
