# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_auto_20161014_0045'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammenu',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='teammenu',
            name='group',
        ),
        migrations.RemoveField(
            model_name='teammenu',
            name='menu',
        ),
        migrations.AlterUniqueTogether(
            name='teammodule',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='teammodule',
            name='module',
        ),
        migrations.RemoveField(
            model_name='teammodule',
            name='team',
        ),
        migrations.AlterUniqueTogether(
            name='teamsubmenu',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='teamsubmenu',
            name='group_menu',
        ),
        migrations.RemoveField(
            model_name='teamsubmenu',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='team',
            name='module',
            field=models.ManyToManyField(related_name='team_team_module', to='team.Module'),
        ),
        migrations.DeleteModel(
            name='TeamMenu',
        ),
        migrations.DeleteModel(
            name='TeamModule',
        ),
        migrations.DeleteModel(
            name='TeamSubMenu',
        ),
    ]
