# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160909_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='register_accountant',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
