# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160910_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ContributionSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('number_account', models.CharField(blank=True, max_length=20, null=True)),
                ('plame', models.CharField(blank=True, max_length=12, null=True)),
                ('percentage_bonus', models.DecimalField(decimal_places=4, default=0, max_digits=8, null=True)),
                ('top', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Correlative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('type_correlative', models.CharField(choices=[('CRT-1', 'Factura'), ('CRT-2', 'Boleta'), ('CRT-3', 'Cotizacion'), ('CRT-4', 'Checklist')], max_length=2)),
                ('prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('postfix', models.CharField(blank=True, max_length=20, null=True)),
                ('format', models.CharField(blank=True, max_length=20, null=True)),
                ('initial', models.IntegerField(default=1)),
                ('increment', models.IntegerField(default=1)),
                ('final', models.IntegerField(blank=True, null=True)),
                ('actual', models.IntegerField(default=0)),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_correlative_subsidiary', to='core.Subsidiary')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TypeContributionSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('type_contribution', models.CharField(choices=[('CTS-1', 'ONP'), ('CTS-2', 'AFP'), ('CTS-3', 'ESSALUD'), ('CTS-4', 'EPS'), ('CTS-5', 'SCTR-SALUD'), ('CTS-6', 'SCTR-PENSION')], max_length=1)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UnitMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('type_correlative', models.CharField(choices=[('UPM-1', 'PURCHASE UNIT'), ('UPM-2', 'PURCHASE UNIT'), ('UPM-3', 'TRANSPORT UNIT'), ('UPM-4', 'DELIVERY UNIT'), ('UPM-5', 'STORAGE UNIT')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contributionsystem',
            name='type_contribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_contributionsystem_type_contribution', to='core.TypeContributionSystem'),
        ),
    ]
