# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160911_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='symbol',
            new_name='code',
        ),
        migrations.AddField(
            model_name='currency',
            name='is_complimentary',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='currency',
            name='is_fund',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='currency',
            name='is_metal',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='currency',
            name='sk',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
