# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160912_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='primary_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_organization_currency', to='core.Currency'),
        ),
    ]
