# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_auto_20160911_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_doc_blood', models.CharField(choices=[('BLR-1', 'Toxicologico'), ('BLR-2', 'Alcoholemia'), ('BLR-3', 'Toxicológico/Alcoholemia')], max_length=10)),
                ('date_emission', models.DateField()),
                ('result_type_doc_blood', models.CharField(choices=[('STBLR-1', 'Negativo'), ('STBLR-2', 'Positivo')], max_length=10)),
                ('observation', models.TextField(blank=True, max_length=200, null=True)),
                ('file_blood', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BloodRelative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, choices=[('', '--Choose--'), ('DOC-1', 'DNI'), ('DOC-2', 'RUC'), ('DOC-3', 'PASSPORT')], max_length=20, null=True)),
                ('document_number', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='last name')),
                ('kinship', models.CharField(choices=[('KSP-1', 'Hijo'), ('KSP-2', 'esposo(a)'), ('KSP-3', 'conviviente')], max_length=10)),
                ('birth_date', models.DateField()),
                ('file_kinship', models.FileField(blank=True, null=True, upload_to='kinship/')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, choices=[('', '--Choose--'), ('DOC-1', 'DNI'), ('DOC-2', 'RUC'), ('DOC-3', 'PASSPORT')], max_length=20, null=True)),
                ('document_number', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='last name')),
                ('home_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('civil_status', models.CharField(choices=[('CVS-1', 'Single'), ('CVS-2', 'Married'), ('CVS-3', 'Widowed'), ('CVS-4', 'Divorced'), ('CVS-5', 'Separated')], max_length=10)),
                ('gender', models.CharField(choices=[('GEN-1', 'Male'), ('GEN-2', 'Female')], max_length=10)),
                ('stature', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('peso', models.IntegerField(blank=True, null=True)),
                ('type_brevete', models.CharField(choices=[('BRT-1', 'A1'), ('BRT-2', 'A2')], max_length=10)),
                ('number_license_brevete', models.CharField(blank=True, max_length=20, null=True)),
                ('number_pension', models.CharField(blank=True, max_length=12, verbose_name='CUSPP')),
                ('is_affiliate_surefire', models.BooleanField(default=False)),
                ('is_affiliate_syndicate', models.BooleanField(default=False)),
                ('type_via', models.CharField(choices=[('VIA-1', 'VIA URBANA'), ('VIA-2', 'VIA INTER-URBANA'), ('VIA-3', 'VIA TRAVESIA'), ('VIA-4', 'VIA CARRETERA'), ('VIA-5', 'VIA TRAVESIA'), ('VIA-6', 'VIA AUTO-PISTA'), ('VIA-7', 'VIA PEAJE')], max_length=10)),
                ('name_via', models.CharField(blank=True, max_length=150)),
                ('nro_via', models.CharField(blank=True, max_length=10, null=True)),
                ('interior', models.CharField(blank=True, max_length=10, null=True)),
                ('manzana', models.CharField(blank=True, max_length=20, null=True)),
                ('type_zone', models.CharField(choices=[('ZNE-1', 'ZONA RESIDENCIAL'), ('ZNE-2', 'ZONA COMERCIAL'), ('ZNE-3', 'VIA TRAVESIA')], max_length=10)),
                ('name_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('residence', models.CharField(blank=True, max_length=255)),
                ('observations', models.TextField(blank=True, null=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to='foto/')),
                ('dni', models.FileField(blank=True, null=True, upload_to='dni/')),
                ('qualification', models.CharField(choices=[('QAL-1', 'MUY_BAJA'), ('QAL-2', 'BAJA'), ('QAL-3', 'MEDIA'), ('QAL-4', 'ALTA'), ('QAL-5', 'MUY_ALTA')], default='3', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('number_bank_account', models.CharField(blank=True, max_length=20, null=True)),
                ('number_interbanking', models.CharField(blank=True, max_length=20, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_employee_bank', to='core.Bank')),
                ('pension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_employee_pension', to='core.ContributionSystem')),
                ('salud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_employee_salud', to='core.ContributionSystem')),
                ('sctr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_employee_sctr', to='core.ContributionSystem')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_employee_specialty', to='core.Specialty')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_employee_subsidiary', to='core.Subsidiary')),
                ('type_pension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_employee_type_pension', to='core.TypeContributionSystem')),
            ],
        ),
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_eps_employee', to='employee.Employee')),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_eps_eps', to='core.ContributionSystem')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=120)),
                ('ruc_company', models.CharField(max_length=120)),
                ('initial', models.DateField()),
                ('final', models.DateField()),
                ('type_document', models.CharField(choices=[('EXR-1', 'Certificado'), ('EXR-2', 'Boleta'), ('EXR-3', 'Planilla')], max_length=10)),
                ('file_type_document', models.FileField(blank=True, null=True, upload_to='exp_record/')),
                ('total_mes', models.IntegerField(blank=True, default=0, null=True)),
                ('Specialty_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_experiencerecord_specialty', to='core.Specialty')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_experiencerecord_employee', to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateField()),
                ('type_doc_police', models.CharField(choices=[('PLR-1', 'Con antecendentes'), ('PLR-2', 'Sin antecendentes')], max_length=10)),
                ('result_type_doc_police', models.CharField(choices=[('STBLR-1', 'Negativo'), ('STBLR-2', 'Positivo')], max_length=10)),
                ('observation', models.TextField(blank=True)),
                ('file_police', models.FileField(blank=True, null=True, upload_to='police_record/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_policerecord_employee', to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_institution', models.CharField(max_length=120)),
                ('course', models.TextField(max_length=100)),
                ('initial', models.DateField()),
                ('final', models.DateField()),
                ('file_trainer', models.FileField(blank=True, null=True, upload_to='exp_trainer/')),
                ('total_dias', models.IntegerField(blank=True, default=0, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_trainingrecord_employee', to='employee.Employee')),
            ],
        ),
        migrations.AddField(
            model_name='bloodrelative',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_bloodrelative_employee', to='employee.Employee'),
        ),
        migrations.AddField(
            model_name='bloodrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_bloodrecord_employee', to='employee.Employee'),
        ),
    ]
