# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20161008_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_userprofile_organization', to='company.Organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subsidiary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_userprofile_subsidiary', to='company.Subsidiary'),
            preserve_default=False,
        ),
    ]
